title: "MetaverseBot.io"
description: "AI-powered insights on the Metaverse, Web3, and blockchain worlds — explore the next frontier of digital intelligence."
url: "https://metaversebot.io"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 6
paginate_path: "/page:num/"

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

google_analytics: "G-9F89QC7PRD"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Alex Reed – AI Metaverse Analyst"
