title: "MetaverseBot.io"
description: "AI-powered insights on Metaverse, gaming, and blockchain worlds."
baseurl: ""
url: "https://metaversebot.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
