title: "MetaverseBot"
description: "MetaverseBot — AI agents, metaverse experiences & Web3 automation."
baseurl: ""
url: "https://metaversebot.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
permalink: /:categories/:year/:month/:day/:title.html
