title: "MetaverseBot.io"
description: "AI-powered insights on the Metaverse, gaming, and blockchain worlds."
url: "https://metaversebot.io"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
