name: Auto Generate Daily Jekyll Post
on:
  schedule:
    - cron: '0 2 * * *'   # 02:00 UTC ~= 09:00 VN
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requests
        run: pip install requests
      - name: Run generator
        run: |
          python3 auto_generate.py
      - name: Commit new posts
        run: |
          git config user.name "Auto Bot"
          git config user.email "auto@users.noreply.github.com"
          git add _posts || true
          if git diff --cached --quiet; then
            echo "No new posts"
          else
            git commit -m "📰 Auto post $(date -u +'%Y-%m-%d %H:%M UTC')"
            git push
          fi
